### ISSUE TITLE
Exception on SNS publish if default region unset or mismatch

### ISSUE THREAD

**Issue by cralston0** [prismskylabs/aws-snapper#4]

**Comment by cralston0** [comment]
Traceback (most recent call last):
  File "aws-snapper/aws-snapper.py", line 184, in <module>
    snapper.daily_run()
  File "aws-snapper/aws-snapper.py", line 180, in daily_run
    self.generate_report()
  File "aws-snapper/aws-snapper.py", line 168, in generate_report
    sns = boto3.resource('sns')
  File "/usr/local/lib/python2.7/dist-packages/boto3/**init**.py", line 87, in resource
    return _get_default_session().resource(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 277, in resource
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 199, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 761, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 59, in create_client
    verify, credentials, scoped_config, client_config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 191, in _get_client_args
    endpoint_url)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 114, in _get_signature_version_and_region
    service_model.endpoint_prefix, region_name, scheme=scheme)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 70, in construct_endpoint
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
