### ISSUE TITLE
Exception when autosnap tags are empty string

### ISSUE THREAD

**Issue by cralston0** [prismskylabs/aws-snapper#6]
Traceback (most recent call last):
  File "aws-snapper/aws-snapper.py", line 184, in <module>
    snapper.daily_run()
  File "aws-snapper/aws-snapper.py", line 179, in daily_run
    self.scan_and_snap(region)
  File "aws-snapper/aws-snapper.py", line 140, in scan_and_snap
    while len(snap_list) > int(v_snap_retain):
ValueError: invalid literal for int() with base 10: ''

**Comment by cralston0** [comment]
Still happening:

Traceback (most recent call last):
  File "aws-snapper/aws-snapper.py", line 184, in <module>
    snapper.daily_run()
  File "aws-snapper/aws-snapper.py", line 179, in daily_run
    self.scan_and_snap(region)
  File "aws-snapper/aws-snapper.py", line 124, in scan_and_snap
    interval = int(v_snap_interval)
ValueError: invalid literal for int() with base 10: ''

**Comment by cralston0** [comment]
False alarm. I was on an outdated branch.
